dings

diff --git a/.github/workflows/idk.yml b/.github/workflows/idk.yml
--- a/.github/workflows/idk.yml
+++ b/.github/workflows/idk.yml
@@ -9,14 +9,31 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Get the tag
+      - name: Check if tag is valid
+        id: validate_tag
         run: |
           regex="^v([0-9]{2}\.){4}[0-9]{2}$"
-          if [[ ${GITHUB_REF#refs/tags/} =~ $regex ]]; then
-          echo "The string is valid."
-          echo "Tag is ${GITHUB_REF#refs/tags/}"
+          TAG="${GITHUB_REF#refs/tags/}"
+          if [[ "$TAG" =~ $regex ]]; then
+            echo "The tag \"$TAG"\ is valid."
           else
-          echo "The string is not valid."
+            echo "The tag is not valid."
+            exit 0  # Just exit without failing, to stop the workflow here
+          fi
+
+      - name: Check if release exists
+        run: |
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+          echo "Checking if release exists for tag: $TAG_NAME"
+          
+          RELEASE=$(curl --silent --fail -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME")
+
+          if [ -z "$RELEASE" ]; then
+            echo "No release exists for tag $TAG_NAME"
+            exit 1
+          else
+            echo "Release exists for tag $TAG_NAME"
           fi
 
 # jobs:
